---
- import_tasks: install.yml
  when: fluentb_log_install|bool
  tags: [fluentb_log_install, install, superuser]

- name: create fluentb user
  user: name=fluentb

- block:
  - name: configure systemd service
    template: src=service.j2 dest='/etc/systemd/system/{{ fluentb_log_service }}.service'
    when: ansible_service_mgr == "systemd"
    notify:
      - restart fluentb service
      - systemd daemon reload
  - name: disable td-agent-bit
    systemd: name=td-ageng-bit enabled=no
    notify: systemd daemon reload
  when: ansible_service_mgr == "systemd"
- block:
  - name: configure init.d script
    template: src=initd.sh.j2 dest='/etc/init.d/{{ fluentb_log_service }}' mode=+x
    notify: restart fluentb service
  - name: link init script to 2 runlevel
    file: src='/etc/init.d/{{ fluentb_log_service }}' state=link
          dest='/etc/rc2.d/S99{{ fluentb_log_service }}'
  when: ansible_service_mgr != "systemd"

- name: configure fluentb agent
  template: src=conf.j2 dest='{{ fluentb_log_config }}' owner=fluentb
            group=fluentb
  notify: restart fluentb service

- name: configure parsers
  template: src=parsers.j2 dest='{{ fluentb_log_parsersfile }}' owner=fluentb
            group=fluentb

- name: ensure fluentb service is running
  service: name='{{ fluentb_log_service }}' state=started
