---
- name: systemd daemon reload
  systemd: daemon_reload=yes state=restarted name='{{ fluentb_log_service }}'
  become: true

- name: restart fluentb service
  service: name='{{ fluentb_log_service }}' state=restarted
  become: true
